### ISSUE TITLE
PHP7.2 imap extension + NGINX issues

### ISSUE THREAD

**Issue by scrnjakovic** [kabel/homebrew-php-ext#11]
Hello there, thanks for the tap.

Upon installing imap with `brew install php@7.2-imap` and enabling it, php-fpm stops working and NGINX reports
```
[error] 196#0: *26 kevent() reported about an closed connection (54: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: hosthere, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9005", host: "hosthere"
```

If I disable imap extension, everyting works fine. PHP-FPM logs show nothing.

Any ideas on how to fix this?

P.S. I pointed PHP-FPM to listen on port 9005 to avoid conflicts with macOS built-in PHP-FPM.

EDIT: actually, PHP-FPM does log following:
```
[08-Feb-2019 03:06:44] WARNING: [pool www] child 18316 exited on signal 11 (SIGSEGV) after 17.982712 seconds from start
[08-Feb-2019 03:06:44] NOTICE: [pool www] child 18318 started
```

Starting PHP-FPM as root fixed it, but only after I had to fix multiple file permission issues.

**Comment by kabel** [comment]
What you're seeing is a segmentation fault (SIGSEGV). You can check the crash report generated in the "User Reports" part of the Console.app. It's interesting that running as root seemed to fix the issue. 

In any case, most program crashes are unlikely to be an issue with the package I put together, but rather something to potentially report upstream to the php team.

**Comment by twmobius** [comment]
I've been pulling my hairs with this one for a day now, and although I am sure that this is not related to your keg I'm writing down my thoughts in case anyone ends up here.

Initially I though that this was related to `gettext` because I managed to trace the problem on a `_('')` line and managed to replicate the `SIGSEGV` with a simple php file containing a simple `echo _('Test');`.

I've also found https://github.com/Homebrew/homebrew-php/issues/1638 which is pretty similar to what I've experienced but on php 7

I tried everything, i.e.

1) Compiling php by hand and intl extension in specific
2) Removing homebrew entirely and reinstalling everything
3) Downgrading from php 7.3 to php@7.2 

I eventually removed all compiled modules (pecl) and tried adding them one after the other. When I added the imap extension it crashed. So I tried installing it via your keg (which does what I did manually) and it still crashed. 

I don't know how it relates with `intl` and `gettext`

Running as root as the post suggests bypasses the problem, (php-fpm drops privilege eventually) and this makes me think that it is definitely some sort of permissions error or library path environment set by homebrew.

Just my 0.02 $
