### ISSUE TITLE
Fetching homebrew-php-ext failed

### ISSUE THREAD

**Issue by DevDavido** [kabel/homebrew-php-ext#29]
Hi,
thank you for the work you put into this repository/tap. 👍 

After making the brew repo unshallow and try to run `brew update` I get the error from `kabel/homebrew-php-ext`:

```
fatal: couldn't find remote ref refs/heads/master
Error: Fetching /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext failed!
```

**Comment by kabel** [comment]
https://github.com/kabel/homebrew-php-ext#troubleshooting

**Comment by panosru** [comment]
@kabel, even after running `brew update-reset`:

```
==> Fetching /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext...
fatal: couldn't find remote ref refs/heads/master
error: Not a valid ref: refs/remotes/origin/main

==> Resetting /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.
```

I'm still getting an error when I run `brew update`:

```
fatal: couldn't find remote ref refs/heads/master
Error: Fetching /usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext failed!
```

**Comment by panosru** [comment]
btw, I think the error happens normally because inside `/usr/local/Homebrew/Library/Taps/kabel/homebrew-php-ext/.git/config` you can see:

```ini
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
	autocrlf = false
[remote "origin"]
	url = https://github.com/kabel/homebrew-php-ext
	fetch = +refs/heads/master:refs/remotes/origin/master
[branch "master"]
	remote = origin
	merge = refs/heads/master
[homebrew]
	private = false
```

It is looking for `master` branch, but the `master` branch in this repo has been renamed to `main` due to the new politically correct crap, I mean policies that GitHub introduced.

Editing the file manually and replace `master` with `main` in the config file and then run `brew update-reset` fixed the issue.

**Comment by DevDavido** [comment]
As @panosru mentioned running `brew update-reset` brings up the same error like he posted. `brew doctor` didn't help either.

**Comment by panosru** [comment]
@DevDavido, just follow my latest post and you will be good to go ;)

**Comment by kabel** [comment]
Sad to see the brew commands are a bit fragile. The other option is to untap and retap.

**Comment by panosru** [comment]
@kabel, I believe that in current situation, brew is not to blame, github decided to go a more PC way, which many, including me, don't like, but still, it is githubs' decision; thus, when it came into effect, brew broke because it was pointing to a reference that no longer exists. Untap and tap is the easier solution, which actually I believe is the best compared to the one I provided above.

**Comment by kabel** [comment]
I appreciate your feedback, but please keep the divisive language to a minimum. I made the conscious decision to change default branch names, fully knowing there would likely be some hiccups.

**Comment by panosru** [comment]
Thankfully github gave the option to us to decide how we like to proceed, otherwise I would've be moving :) Cheers
